# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13pZD1jgnu__sWCI8M9uKjvCgN2ycup8m
"""

N=int(input('enter value of N:'))

note1=N/2
note2=N/3
note3=N/4

print(note1)
if note1==N/2:
   sum1=(note1//2)+(note1//3)+(note1//4)
   rem=(note1/2)+(note1/3)+(note1/4)
   print(sum1,rem)
   add_no=rem-sum1   #### additional no get introduce in it
   add_no=int(add_no)
   print(add_no)

print(note2)
if note2==N/3:
  sum2=(note2//2)+(note2//3)+(note2//4)
  print(sum2)
###########################3
  '''rem2=(note2/2)+(note2/3)+(note2/4)
  print(sum2,rem2)
  add_no2=rem2-sum2
  add_no2=int(add_no2)
  print(add_no2)'''

print(note3)
if note3==N/4:
  sum3=(note3//2)+(note3//3)+(note3//4)
  print(sum3)

output=sum1+sum2+sum3+add_no
output